name: Build and upload sdist Package to PyPI

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine flake8
    - name: Create sdist
      run: |
        python setup.py sdist
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/*.tar.gz
    - name: Publish sdist to PyPI
      if: ${{ success() && github.event_name == 'release' && github.event.action == 'created' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_FORLILAB }}
      run: |
        twine upload dist/*.tar.gz